#!/usr/bin/env bash

## path
PATH="$HOME/.config/bspwm/scripts:$PATH"
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

bspc monitor eDP -d ''  ''  ''  ''  ''  ''  ''  ''  ''  ''
bspc config border_width 0
bspc config top_padding 0
bspc config bottom_padding 2
bspc config normal_border_color "#414868"
bspc config active_border_color "#c0caf5"
bspc config focused_border_color "#bb9af7"
bspc config presel_feedback_color "#7aa2f7"
bspc config left_padding 0
bspc config right_padding 2
bspc config window_gap 8

bspc config split_ratio 0.50
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#bspc wm --adopt-orphans
bspc rule -r "*"
bspc rule -a firefox desktop='^1'
bspc rule -a eu.betterbird.Betterbird desktop='^2'
bspc rule -a Claws-mail desktop='^2'
bspc rule -a wattage state=floating center=on 
bspc rule -a shutter state=floating center=on

# Terminate already running polybar, eww, picom, sxhkd and dunst instances
processes=("picom" "polybar" "eww" "sxhkd" "dunst")

for process in "${processes[@]}"; do
  if pidof -q "$process"; then
    pkill -9 -x "$process" > /dev/null; sleep 0.1
  fi
done

# Load bars and/or eww widgets
polybar -q &

# Launch picom // If you have old hardware or encounter problems
# uncomment the picom "--legacy-backends" line and comment the current one.
picom --config "$HOME"/.config/bspwm/picom.conf &

# Launch dunst notification daemon
dunst -conf "$HOME"/.config/bspwm/dunstrc &

# Set random wallpaper for actual rice
feh -z --no-fehbg --bg-fill "$HOME"/.config/bspwm/ryan/walls &

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Launch polkit
/usr/lib/policykit-gnome/polkit-gnome-authentication-agent-1 &

# Fix cursor
xsetroot -cursor_name left_ptr &

#clipboard
greenclip daemon &

#Xresources
# xrdb merge "$HOME"/.Xresources &

bspi_listen --config ~/.config/bspwm/bspi.ini &

clamd &

echo 120 > /sys/class/backlight/amdgpu_bl1/brightness &

killall redshift
sleep 5
redshift -c ~/.config/redshift/redshift.conf & 
