;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #1a1b26
background-alt = #24283b
foreground = #c0caf5
primary = #e0af68
secondary = #9ece6a
alert = #db4b4b
disabled = #414868
blue = #7aa2f7
red = #f4155a
pink = #f200f4
purple = #6800d2
cyan = #4DD0E1
teal = #00B19F
green = #00ff00
lime = #8df202
yellow = #f2ed00
amber = #FBC02D
orange = #db330a
brown = #AC8476
grey = #8C8C8C
indigo = #8f32e4
bluegray = #1e80d2  

[bar/ryan-bar]
monitor = ${env:MONITOR:}
width = 98%
height = 22
radius = 6
fixed-center = true
bottom = true
offset-x = 1%
offset-y = 5

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2

border-size = 7pt
border-color = ${colors.background}

padding = 1

module-margin-left = 0
module-margin-right = 0

font-0 = RobotoMono Nerd Font:style=Regular:size=11;2
font-3 = Font Awesome 5 Free:pixelsize=20;3
font-4 = Font Awesome 5 Free Solid:pixelsize=20;3
font-5 = Font Awesome 5 Brands:pixelsize=20;3

modules-left = launcher spasi xworkspaces spasi
modules-center = xwindow
modules-right = spasi cpu spasi network spasi pulseaudio spasi date spasi sysmenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
wm-restack = bspwm

include-file = ~/.config/bspwm/scripts/system.ini
include-file = modules.ini 
include-file = gylphs.ini

[settings]
screenchange-reload = true
pseudo-transparency = true

