#!/usr/bin/env bash

wid=$1
class=$2
instance=$3
consequences=$4

main () {
case "$class" in
	FloaTerm)
		eval "$consequences"
		[ "$state" ] || echo "state=floating center=on"
		;;
	Updating)
		eval "$consequences"
		[ "$state" ] || echo "state=floating sticky=on center=on"
		;;
	Pavucontrol)
	    eval "$consequences"
	    [ "$state" ] || echo "state=floating center=on"
	    ;;
        sleep 0.5
		wm_class=($(xprop -id $wid | grep "WM_CLASS" | grep -Po '"\K[^,"]+'))
		class=${wm_class[-1]}
		[[ ${#wm_class[@]} == "2" ]] && instance=${wm_class[0]}
		[[ -n "$class" ]] && main
		;;
esac
}

main
case "$instance" in
     Toolkit)
        eval "$consequences"
        [ "$state" ] || echo "state=floating sticky=on rectangle=500x290"
	    ;;
esac  
